# 예외 처리
- 예외가 프로그램의 오류나 다운으로 이어지지 않도록 적절하게 처리하는 것 
- ---
## 1. try ~ catch로 예외 받기
- C#에서는 예외를 받을 때 try ~ catch문을 이용함 

```cs
try
{
    // 실행하고자 하는 코드
} 
catch(예외_객체_1)
{
    // 예외가 발생했을 때의 처리
}
catch (예외_객체_2)
{
    // 예외가 발생했을 때의 처리
}
```
- catch 절은 try 블록에서 던질 예외 객체와 형식이 일치해야함
- 일치하지 않으면 던져진 예외는 아무도 받지 못해 "처리되지 않은 예외"로 남음 

ex) 잘못된 인덱스를 통해 배열의 요소에 접근 예외 처리
```cs
static void Main(string[] args)
{
    int[] arr = { 1, 2, 3 };

    try
    {
        for (int i = 0; i < 5; i++)
        {
            Console.WriteLine(arr[i]);
        }
        catch(IndexOutOfRangeException e)
        {
            Console.WriteLine($"예외 발생 : {e.Message}");
        }

        Cosole.WriteLine("종료");
    }
}

>>> 
1
2
3
예외 발생 : 인덱스가 배열 범위를 벗어났습니다.
종료
```
---
## 2. System.Exception 클래스
- C#에서 모든 예외 클래스는 반드시 System.Exception 클래스로부터 상속받아야 함
- 그러므로 System.Exception 형식의 예외를 받는 catch 절 하나면 모든 예외를 다 받아낼수 있음 
```cs
try
{
}
catch( Exceptio e)
{
} 
```
---
## 3. 예외 던지기
- try ~ catch 문으로 예외를 받는다는 것은 어디선가 예외를 던진다는 것 
- throw를 이용해 예외를 던짐 
```cs
try
{
    // ...
    throw new Exception("예외를 던집니다");
} 
catch (Exception e)
{
    Console.WriteLine(e.Message);
}
```
---
## 4. try ~ catch와 finally 
- try에서 코드를 실행하다 예외가 던져지면 try 블록의 자원 해제 같은 중요한 코드들이 미쳐 실행되지 않게되고 이는 버그를 만드는 원인 
- C#에서는 자원 해제 같은 코드들을 마무리 할 수 있도록 finally 절을 제공
```cs
try
{
    dbconn.Open();
    //...
}
catch (Exception e)
{
    //..
}
finally
{
    dbconn.Close();
}
```
- finally가 소속된 try절이 실행된다면 finally 절은 반드시 실행 
- **try문에 return이나 throw가 있어도 실행**
- finally 안에서 예외가 일어난다면 처리되지 않은 예외가 됌
---
## 5. 사용자 정의 예외 클래스
- C#에서 사용하는 모든 예외 객체는 System.Exception 클래스로부터 파생되어야 함 
- 즉, Exception 클래스를 상속하기만 하면 새로운 예외 클래스를 만들 수 있음 
```cs
class MyException : Exception
{
    //...
}
```
---
## 6. 예외 필터
- catch 절이 받아들일 예외 객체에 제약 사항을 걸어 조건을 만족하는 예외 객체에 대해서만 실행할 수 있도록 하는 것 
- catch() 절 뒤에 when 키워드를 이용하여 제약 조건 기술 
```cs
class FilterableException : Exception
{
    public int ErrorNo {get; set;}
}

try
{
    int num = GetNumber();

    if (num <0 || num > 10)
        throw new FilterableException() { ErrorNo = num};
    else 
        Console.WriteLine($"Output : {num});
}
catch (FilterableException e) when (e.ErrorNo < 0)
{
    Cosole.WriteLine("Negative input in not allowed")
}
```


